#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
source "$SCRIPT_DIR/config.sh"

# Clones/pulls the repo, syncs backend deps, runs Alembic migrations, and
# (re)installs the systemd service. Safe to re-run for redeploys - this is
# also what deploy.sh calls.

if [ ! -d "$APP_DIR/.git" ]; then
  echo "==> Cloning $REPO_URL ($BRANCH) into $APP_DIR"
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
else
  echo "==> Updating existing checkout in $APP_DIR"
  git -C "$APP_DIR" fetch origin "$BRANCH"
  git -C "$APP_DIR" checkout "$BRANCH"
  git -C "$APP_DIR" pull --ff-only origin "$BRANCH"
fi

cd "$APP_DIR/backend"

if [ ! -f .env ]; then
  echo "==> Creating backend/.env from .env.example"
  cp .env.example .env
  sed -i "s#^DATABASE_URL=.*#DATABASE_URL=postgresql+psycopg://$PG_APP_USER:$PG_APP_PASSWORD@localhost:5432/$PG_APP_DB#" .env
  echo "    Review backend/.env - VAPID_* keys are still blank (only needed for web push)."
fi

echo "==> uv sync"
uv sync --frozen --no-dev

echo "==> Running Alembic migrations"
echo "    NOTE: alembic/versions/*_create_bed_table.py was hand-written, not autogenerated,"
echo "    and this may be the first time it has run against a real Postgres. Watch the output."
uv run alembic upgrade head

echo "==> Installing systemd unit"
sed \
  -e "s#__APP_DIR__#$APP_DIR#g" \
  -e "s#__USER__#$SERVICE_USER#g" \
  -e "s#__BACKEND_BIND_HOST__#$BACKEND_BIND_HOST#g" \
  -e "s#__BACKEND_PORT__#$BACKEND_PORT#g" \
  "$SCRIPT_DIR/garden-backend.service.template" | sudo tee "/etc/systemd/system/$SERVICE_NAME.service" >/dev/null

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"

echo "==> Waiting for backend to come up"
sleep 2
if curl -fsS "http://$BACKEND_HOST:$BACKEND_PORT/api/health"; then
  echo
  echo "==> Backend OK - reachable on the LAN at http://<this-host-ip>:$BACKEND_PORT (bound to $BACKEND_BIND_HOST), incl. /docs."
  echo "==> Next: 04-deploy-frontend.sh"
else
  echo "Backend health check failed - check: sudo journalctl -u $SERVICE_NAME -n 50" >&2
  exit 1
fi
