#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
source "$SCRIPT_DIR/config.sh"

# Clones/pulls the repo, syncs backend deps, runs Alembic migrations, and
# (re)installs the systemd service. Safe to re-run for redeploys - this is
# also what deploy.sh calls.

# Identity preflight. Everything downstream (file ownership, SERVICE_USER in
# the systemd unit) assumes this script runs as the one account that owns
# $APP_DIR - catch a root/deploy (or similar) mismatch here, with a clear
# fix, instead of letting it surface as a cryptic git/permission error deep
# in the script, or a systemd unit silently running as the wrong user.
if [ -e "$APP_DIR" ]; then
  APP_DIR_OWNER="$(stat -c '%U' "$APP_DIR")"
  if [ "$APP_DIR_OWNER" != "$(whoami)" ]; then
    echo "ERROR: $APP_DIR is owned by '$APP_DIR_OWNER', not '$(whoami)' (the user running this script)." >&2
    echo "This usually means an earlier run happened under a different identity (e.g. root via 'sudo -i')." >&2
    echo "Fix: sudo chown -R $(whoami):$(whoami) $APP_DIR" >&2
    exit 1
  fi
fi
if [ "$SERVICE_USER" != "$(whoami)" ]; then
  echo "ERROR: SERVICE_USER is '$SERVICE_USER' (config.sh) but this script is running as '$(whoami)'." >&2
  echo "The systemd unit would end up configured to run as the wrong user. Run this as '$SERVICE_USER', or fix SERVICE_USER in config.sh." >&2
  exit 1
fi

# uv installs to ~/.local/bin (01-install-packages.sh). That's only on PATH
# in a shell that has sourced .profile/.bashrc since - not guaranteed if this
# runs in the same session uv was just installed in. Don't rely on it.
export PATH="$HOME/.local/bin:$PATH"
if ! command -v uv >/dev/null 2>&1; then
  echo "uv not found (checked PATH and ~/.local/bin). Run 01-install-packages.sh as this user first." >&2
  exit 1
fi
UV_PATH="$(command -v uv)"

if [ -z "${GARDEN_DEPLOY_REEXEC:-}" ]; then
  if [ ! -d "$APP_DIR/.git" ]; then
    echo "==> Cloning $REPO_URL ($BRANCH) into $APP_DIR"
    git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
  else
    echo "==> Updating existing checkout in $APP_DIR"
    git -C "$APP_DIR" fetch origin "$BRANCH"
    git -C "$APP_DIR" checkout "$BRANCH"
    git -C "$APP_DIR" pull --ff-only origin "$BRANCH"
  fi

  # This script may have just pulled a newer version of itself. Bash keeps
  # executing the in-memory copy it originally opened, not the one now on
  # disk, so anything below this point could otherwise run stale logic
  # against already-updated files (has bitten this exact pipeline before -
  # see the "self-updating-script gotcha" note in CLAUDE.md). Re-exec to
  # force a fresh read from disk; the guard var stops this from looping.
  exec env GARDEN_DEPLOY_REEXEC=1 "$SCRIPT_DIR/03-deploy-backend.sh" "$@"
fi

cd "$APP_DIR/backend"

if [ ! -f .env ]; then
  echo "==> Creating backend/.env from .env.example"
  cp .env.example .env
  sed -i "s#^DATABASE_URL=.*#DATABASE_URL=postgresql+psycopg://$PG_APP_USER:$PG_APP_PASSWORD@localhost:5432/$PG_APP_DB#" .env
  echo "    Review backend/.env - VAPID_* keys are still blank (only needed for web push)."
fi

echo "==> uv sync"
uv sync --frozen --no-dev

echo "==> Running Alembic migrations"
echo "    NOTE: alembic/versions/*_create_bed_table.py was hand-written, not autogenerated,"
echo "    and this may be the first time it has run against a real Postgres. Watch the output."
uv run alembic upgrade head

echo "==> Installing systemd unit"
sed \
  -e "s#__APP_DIR__#$APP_DIR#g" \
  -e "s#__USER__#$SERVICE_USER#g" \
  -e "s#__UV_PATH__#$UV_PATH#g" \
  -e "s#__BACKEND_BIND_HOST__#$BACKEND_BIND_HOST#g" \
  -e "s#__BACKEND_PORT__#$BACKEND_PORT#g" \
  "$SCRIPT_DIR/garden-backend.service.template" | sudo tee "/etc/systemd/system/$SERVICE_NAME.service" >/dev/null

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"

echo "==> Waiting for backend to come up"
sleep 2
if curl -fsS "http://$BACKEND_HOST:$BACKEND_PORT/api/health"; then
  echo
  echo "==> Backend OK - reachable on the LAN at http://<this-host-ip>:$BACKEND_PORT (bound to $BACKEND_BIND_HOST), incl. /docs."
  echo "==> Next: 04-deploy-frontend.sh"
else
  echo "Backend health check failed - check: sudo journalctl -u $SERVICE_NAME -n 50" >&2
  exit 1
fi
