"""plant water_needs_mm_per_week

Revision ID: 1f6a2c9d4b8e
Revises: e2c5a917b6d4
Create Date: 2026-07-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6a2c9d4b8e'
down_revision: Union[str, Sequence[str], None] = 'e2c5a917b6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. Purely structural (#138): replaces the
# free-text `water_needs` column with a numeric `water_needs_mm_per_week`
# float column. No in-place string-parsing/data-migration here - a later
# /deploy-data reimport (once the data-engineer sub-issue converts the JSON
# source to the same field name) repopulates real values, same pattern as
# growth_habit (e2c5a917b6d4).


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "plant", sa.Column("water_needs_mm_per_week", sa.Float(), nullable=True)
    )
    op.drop_column("plant", "water_needs")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column("plant", sa.Column("water_needs", sa.String(), nullable=True))
    op.drop_column("plant", "water_needs_mm_per_week")
