"""create irrigation_zone table

Revision ID: 2a4d7e91c3b6
Revises: 1f6a2c9d4b8e
Create Date: 2026-07-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4d7e91c3b6'
down_revision: Union[str, Sequence[str], None] = '1f6a2c9d4b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. #36: drip irrigation zone grouping - a small
# lookup table (id/name/notes) plus a nullable zone_id FK on bed_equipment,
# not a many-to-many join table (see app/models/irrigation_zone.py's
# docstring for why). No ON DELETE CASCADE/SET NULL at the DB level -
# irrigation_zones.delete_irrigation_zone unassigns member equipment
# explicitly before deleting the zone row, same manual-cleanup style
# plants.py's delete_plant already uses.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "irrigation_zone",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
    )
    op.add_column(
        "bed_equipment",
        sa.Column(
            "zone_id",
            sa.Integer(),
            sa.ForeignKey("irrigation_zone.id"),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("bed_equipment", "zone_id")
    op.drop_table("irrigation_zone")
