"""create garden plan tables

Revision ID: 79f4a5571f9d
Revises: 9d1c6f2a4e0b
Create Date: 2026-07-21 13:17:11.253408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f4a5571f9d'
down_revision: Union[str, Sequence[str], None] = '9d1c6f2a4e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated: alembic/env.py's target_metadata only
# imports app.models.bed/plant (a pre-existing gap predating this
# migration - it doesn't import app.models.garden/planting/bed_equipment
# either), so `alembic revision --autogenerate` against garden_test comes
# back thinking those tables were "removed" and emits DROP TABLE
# statements for them. Verified that broken output, discarded it, and
# wrote this by hand instead - same approach the original
# 8ece1e150dae_create_bed_table.py migration used for the same reason.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "garden_plan",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("season_name", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )
    op.create_table(
        "garden_plan_entry",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("garden_plan_id", sa.Integer(), sa.ForeignKey("garden_plan.id"), nullable=False),
        sa.Column("plant_slug", sa.String(), sa.ForeignKey("plant.slug"), nullable=False),
        sa.Column("bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=True),
        sa.Column("desired_quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("garden_plan_entry")
    op.drop_table("garden_plan")
