"""create compost_fertilization_log table

Revision ID: 9c3f5a8e1d47
Revises: 6b1e9f3a7c52
Create Date: 2026-07-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3f5a8e1d47'
down_revision: Union[str, Sequence[str], None] = '6b1e9f3a7c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #38:
# CompostFertilizationLog - a per-bed log of compost/fertilization events,
# shape matching docs/schema.md's already-sketched COMPOST_FERTILIZATION_LOG
# table (see app/models/compost_fertilization_log.py).


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "compost_fertilization_log",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("compost", "fertilizer", name="compostfertilizationlogtype"),
            nullable=False,
        ),
        sa.Column("product", sa.String(), nullable=False, server_default=""),
        sa.Column("amount", sa.String(), nullable=False, server_default=""),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("compost_fertilization_log")
    sa.Enum(name="compostfertilizationlogtype").drop(op.get_bind(), checkfirst=True)
