"""create compost_bin table

Revision ID: a1e4c7b3f962
Revises: 9c3f5a8e1d47
Create Date: 2026-07-28 00:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e4c7b3f962'
down_revision: Union[str, Sequence[str], None] = '9c3f5a8e1d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #39:
# CompostBin - compost-specific state (fill state, last-turned date,
# estimated maturity) for a bed acting as a compost bin, kept as a small
# satellite table 1:1 with bed (bed_id unique) rather than extending Bed
# itself - see app/models/compost_bin.py's own docstring.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "compost_bin",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=False, unique=True),
        sa.Column(
            "fill_state",
            sa.Enum("empty", "filling", "full", "curing", name="compostbinfillstate"),
            nullable=False,
            server_default="empty",
        ),
        sa.Column("last_turned_date", sa.Date(), nullable=True),
        sa.Column("estimated_maturity_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("compost_bin")
    sa.Enum(name="compostbinfillstate").drop(op.get_bind(), checkfirst=True)
