"""multi-garden support: garden.is_active, bed/garden_plan.garden_id

Revision ID: a7c3e9f2b5d1
Revises: f1a2b3c4d5e6
Create Date: 2026-08-04 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c3e9f2b5d1'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #238:
# real multi-garden support - exactly one Garden is "active" at a time
# (garden.is_active), and Bed/GardenPlan each carry a nullable garden_id FK
# (everything else keys off bed_id and is transitively scoped once Bed is -
# see app/models/garden.py's own docstring). Backfill: whatever Garden row
# already exists becomes active and "owns" every existing Bed/GardenPlan
# row - zero user-visible disruption for the single-garden case this app
# has only ever had until now.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "garden", sa.Column("is_active", sa.Boolean(), nullable=False, server_default="false")
    )
    op.add_column("bed", sa.Column("garden_id", sa.Integer(), sa.ForeignKey("garden.id"), nullable=True))
    op.add_column(
        "garden_plan", sa.Column("garden_id", sa.Integer(), sa.ForeignKey("garden.id"), nullable=True)
    )

    # Backfill: the first (lowest-id) existing Garden row, if any, becomes
    # active and owns every pre-existing Bed/GardenPlan row. Multiple
    # pre-existing Garden rows aren't expected (the API was singleton-only
    # before this migration), but ORDER BY id LIMIT 1 keeps this correct
    # (exactly one activated) even if that ever turns out to be wrong.
    op.execute(
        "UPDATE garden SET is_active = true WHERE id = (SELECT id FROM garden ORDER BY id LIMIT 1)"
    )
    op.execute(
        "UPDATE bed SET garden_id = (SELECT id FROM garden ORDER BY id LIMIT 1) WHERE garden_id IS NULL"
    )
    op.execute(
        "UPDATE garden_plan SET garden_id = (SELECT id FROM garden ORDER BY id LIMIT 1) WHERE garden_id IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("garden_plan", "garden_id")
    op.drop_column("bed", "garden_id")
    op.drop_column("garden", "is_active")
