"""create seed_inventory_item table

Revision ID: a7c39e5f2b18
Revises: f1b7e4a92c3d
Create Date: 2026-07-21 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c39e5f2b18'
down_revision: Union[str, Sequence[str], None] = 'f1b7e4a92c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on 79f4a5571f9d and later migrations in this chain.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "seed_inventory_item",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("plant_slug", sa.String(), sa.ForeignKey("plant.slug"), nullable=False),
        sa.Column("quantity_seeds", sa.Float(), nullable=True),
        sa.Column("weight_grams", sa.Float(), nullable=True),
        sa.Column("acquired_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("seed_inventory_item")
