"""add bed_equipment.owned

Revision ID: a8c1e5f39b04
Revises: f40407484fb2
Create Date: 2026-08-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c1e5f39b04'
down_revision: Union[str, Sequence[str], None] = 'f40407484fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated (plain sa.Boolean() add_column - no enum
# lifecycle concerns here, unlike condition's own migration). #255: lets a
# BedEquipment row be created before the physical item is actually owned
# (owned=False), so a shopping list can surface the shortfall - see
# app/models/bed_equipment.py's own docstring on the field. Every existing
# row defaults to True (already-owned equipment), same default the model
# itself uses.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "bed_equipment",
        sa.Column("owned", sa.Boolean(), nullable=False, server_default="true"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("bed_equipment", "owned")
