"""create soil_rotation_event, soil_rotation_transfer, soil_family_history tables

Revision ID: b2d4f6a8c1e3
Revises: a7c3e9f2b5d1
Create Date: 2026-08-04 05:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d4f6a8c1e3'
down_revision: Union[str, Sequence[str], None] = 'a7c3e9f2b5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #228:
# soil rotation - Dave physically moves topsoil between beds every few
# years (N-way cycles, not just pairwise swaps); disease-carryover risk
# travels with the soil, not the bed's physical location. See
# app/models/soil_rotation.py for the full data-model rationale.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "soil_rotation_event",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )
    op.create_table(
        "soil_rotation_transfer",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "soil_rotation_event_id",
            sa.Integer(),
            sa.ForeignKey("soil_rotation_event.id"),
            nullable=False,
        ),
        sa.Column("from_bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=True),
        sa.Column("to_bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=False),
    )
    op.create_table(
        "soil_family_history",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=False),
        sa.Column("family_id", sa.Integer(), sa.ForeignKey("family.id"), nullable=False),
        sa.Column("source_planted_date", sa.Date(), nullable=False),
        sa.Column("source_bed_id", sa.Integer(), nullable=False),
        sa.Column("source_plant_slug", sa.String(), nullable=False),
        sa.Column(
            "soil_rotation_event_id",
            sa.Integer(),
            sa.ForeignKey("soil_rotation_event.id"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("soil_family_history")
    op.drop_table("soil_rotation_transfer")
    op.drop_table("soil_rotation_event")
