"""create action table

Revision ID: b3a7d2e19f45
Revises: 79f4a5571f9d
Create Date: 2026-07-21 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a7d2e19f45'
down_revision: Union[str, Sequence[str], None] = '79f4a5571f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - alembic/env.py's target_metadata only
# imports app.models.bed/plant (a pre-existing gap, see 79f4a5571f9d's own
# note), so autogenerate against garden_test would again misread several
# unrelated tables as "removed". Written by hand instead, same as that one.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "action",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "action_type",
            sa.Enum(
                "fertilize",
                "compost",
                "prepare_bed",
                "sow",
                "plant",
                "install_equipment",
                "remove_equipment",
                "harvest",
                "clear",
                "collect_seeds",
                name="actiontype",
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "skipped", name="actionstatus"),
            nullable=False,
            server_default="pending",
        ),
        sa.Column(
            "garden_plan_entry_id",
            sa.Integer(),
            sa.ForeignKey("garden_plan_entry.id"),
            nullable=True,
        ),
        sa.Column("bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=True),
        sa.Column("plant_slug", sa.String(), sa.ForeignKey("plant.slug"), nullable=True),
        sa.Column("equipment_id", sa.Integer(), sa.ForeignKey("bed_equipment.id"), nullable=True),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("action")
    sa.Enum(name="actiontype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="actionstatus").drop(op.get_bind(), checkfirst=True)
