"""add irrigation_part_instance bed_id/garden_id/geometry placement

Revision ID: b4d8e1a7f3c9
Revises: a8c1e5f39b04
Create Date: 2026-08-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = 'b4d8e1a7f3c9'
down_revision: Union[str, Sequence[str], None] = 'a8c1e5f39b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same pattern every migration in this
# tree uses (see e.g. f7b2d4a6c803, a8c1e5f39b04). #271: real garden/bed-
# space placement for IrrigationPartInstance, needed to merge the
# irrigation editor into the main garden canvas (#250) - additive
# alongside the existing diagram_x/diagram_y columns (kept for the
# standalone pipe-network diagram, see the model's own docstring). All
# three new columns are nullable and every existing row gets NULL - same
# "not yet placed in garden space" semantics BedEquipment.geometry already
# uses for unassigned inventory.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "irrigation_part_instance",
        sa.Column("bed_id", sa.Integer(), sa.ForeignKey("bed.id"), nullable=True),
    )
    op.add_column(
        "irrigation_part_instance",
        sa.Column("garden_id", sa.Integer(), sa.ForeignKey("garden.id"), nullable=True),
    )
    op.add_column(
        "irrigation_part_instance",
        sa.Column("geometry", JSONB(), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("irrigation_part_instance", "geometry")
    op.drop_column("irrigation_part_instance", "garden_id")
    op.drop_column("irrigation_part_instance", "bed_id")
