"""add plant sow_indoors sow_direct needs_thinning

Revision ID: b8e2a4c9f317
Revises: d3c7f9a1b6e2
Create Date: 2026-07-28 03:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e2a4c9f317'
down_revision: Union[str, Sequence[str], None] = 'd3c7f9a1b6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. Purely additive/nullable (#196), same
# true-or-null nullable-boolean convention as needs_wind_cover/
# needs_rain_cover - no backfill here, a later /deploy-data reimport
# (app/scripts/import_plants.py's generic scalar passthrough) repopulates
# real values from data/plants/*.json once these columns exist, same
# pattern as plant_spacing_cm (#194).


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("plant", sa.Column("sow_indoors", sa.Boolean(), nullable=True))
    op.add_column("plant", sa.Column("sow_direct", sa.Boolean(), nullable=True))
    op.add_column("plant", sa.Column("needs_thinning", sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("plant", "needs_thinning")
    op.drop_column("plant", "sow_direct")
    op.drop_column("plant", "sow_indoors")
