"""add decoration.garden_id

Revision ID: c1d4e8a2f6b7
Revises: b4d8e1a7f3c9
Create Date: 2026-08-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d4e8a2f6b7'
down_revision: Union[str, Sequence[str], None] = 'b4d8e1a7f3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier hand-written migrations. #266: Decoration (#241) was
# missed by both #238 (multi-garden support) and #258 (scoping every
# garden-owned list endpoint to the active garden) since it's a purely
# cosmetic, no-FK model that neither touched directly. Adds a nullable
# garden_id FK, same shape as bed.garden_id's own migration
# (a7c3e9f2b5d1_multi_garden_support.py) - no backfill here, unlike that
# migration's Bed/GardenPlan backfill, since #266's own body explicitly
# scopes this to "nullable, matching Bed.garden_id's own reasoning" without
# calling for one, and GET /api/decorations already falls back to
# unfiltered whenever no active garden exists (same as every pre-#238 flow).


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "decoration", sa.Column("garden_id", sa.Integer(), sa.ForeignKey("garden.id"), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("decoration", "garden_id")
