"""create harvest_log table

Revision ID: c4e8f1a26d7b
Revises: b3a7d2e19f45
Create Date: 2026-07-21 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e8f1a26d7b'
down_revision: Union[str, Sequence[str], None] = 'b3a7d2e19f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on 79f4a5571f9d/b3a7d2e19f45.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "harvest_log",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("planting_id", sa.Integer(), sa.ForeignKey("planting.id"), nullable=False),
        sa.Column("harvest_date", sa.Date(), nullable=False),
        sa.Column("yield_amount", sa.Float(), nullable=True),
        sa.Column("yield_unit", sa.String(), nullable=True),
        sa.Column(
            "quality",
            sa.Enum("poor", "fair", "good", "excellent", name="harvestquality"),
            nullable=True,
        ),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("harvest_log")
    sa.Enum(name="harvestquality").drop(op.get_bind(), checkfirst=True)
