"""create irrigation_part and irrigation_connection tables

Revision ID: c7d2f918a4b3
Revises: b8e2a4c9f317
Create Date: 2026-07-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d2f918a4b3'
down_revision: Union[str, Sequence[str], None] = 'b8e2a4c9f317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. #37: parts-catalog + edge-list model for the
# irrigation pipe network, additive to #36's zone-level grouping. No ON
# DELETE CASCADE on irrigation_connection's FKs - irrigation_parts.py's
# delete_irrigation_part deletes referencing connections explicitly before
# deleting the part row, same manual-cleanup style irrigation_zones.py
# already uses for its own member-equipment cleanup.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "irrigation_part",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("part_type", sa.String(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
    )
    op.create_table(
        "irrigation_connection",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "from_part_id",
            sa.Integer(),
            sa.ForeignKey("irrigation_part.id"),
            nullable=False,
        ),
        sa.Column(
            "to_part_id",
            sa.Integer(),
            sa.ForeignKey("irrigation_part.id"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(), nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("irrigation_connection")
    op.drop_table("irrigation_part")
