"""add action.snoozed_until

Revision ID: c9e1a3b5d7f2
Revises: b2d4f6a8c1e3
Create Date: 2026-08-04 06:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e1a3b5d7f2'
down_revision: Union[str, Sequence[str], None] = 'b2d4f6a8c1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #230:
# "remind me later" - suppresses further reminder pushes
# (app/services/reminders.py's due_actions) without touching an action's
# actual due_date_start/due_date_end window. Nullable, no backfill needed -
# every existing Action row simply isn't snoozed.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("action", sa.Column("snoozed_until", sa.Date(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("action", "snoozed_until")
