"""garden_plan_entry.desired_quantity nullable

Revision ID: d2f5b8a1c4e7
Revises: c1d4e8a2f6b7
Create Date: 2026-08-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f5b8a1c4e7'
down_revision: Union[str, Sequence[str], None] = 'c1d4e8a2f6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier hand-written migrations. #276 (split from #267):
# GardenPlanEntry.desired_quantity gets the same "optional - not yet
# assigned" treatment bed_id already has on this table - a wishlist entry
# can exist before a quantity is decided. No backfill needed: existing rows
# already carry a real quantity, this only relaxes the constraint going
# forward.


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "garden_plan_entry", "desired_quantity", existing_type=sa.Integer(), nullable=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column(
        "garden_plan_entry", "desired_quantity", existing_type=sa.Integer(), nullable=False
    )
