"""add plant plant_spacing_cm

Revision ID: d3c7f9a1b6e2
Revises: f4a8c2e517b9
Create Date: 2026-07-28 02:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c7f9a1b6e2'
down_revision: Union[str, Sequence[str], None] = 'f4a8c2e517b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. Purely additive/nullable (#194), same
# *_cm float-column convention as row_spacing_cm/spread_cm/height_cm - no
# backfill here, a later /deploy-data reimport (app/scripts/import_plants.py's
# generic scalar passthrough) repopulates real values from
# data/plants/*.json once the column exists, same pattern as
# water_needs_mm_per_week (#138).


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("plant", sa.Column("plant_spacing_cm", sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("plant", "plant_spacing_cm")
