"""add action recurrence fields

Revision ID: d4f6b8c0a2e5
Revises: c9e1a3b5d7f2
Create Date: 2026-08-04 07:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f6b8c0a2e5'
down_revision: Union[str, Sequence[str], None] = 'c9e1a3b5d7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #226:
# manually-created recurring/repeating tasks (e.g. "turn the compost bin
# every 3 weeks") - all four columns nullable/defaulted, no backfill
# needed, every existing Action row simply isn't recurring.
_recurrence_unit_enum = sa.Enum("daily", "weekly", "monthly", "yearly", name="recurrenceunit")


def upgrade() -> None:
    """Upgrade schema."""
    _recurrence_unit_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("action", sa.Column("recurrence_unit", _recurrence_unit_enum, nullable=True))
    op.add_column(
        "action", sa.Column("recurrence_interval", sa.Integer(), nullable=False, server_default="1")
    )
    op.add_column("action", sa.Column("recurrence_end_date", sa.Date(), nullable=True))
    op.add_column(
        "action",
        sa.Column("recurrence_source_action_id", sa.Integer(), sa.ForeignKey("action.id"), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("action", "recurrence_source_action_id")
    op.drop_column("action", "recurrence_end_date")
    op.drop_column("action", "recurrence_interval")
    op.drop_column("action", "recurrence_unit")
    _recurrence_unit_enum.drop(op.get_bind(), checkfirst=True)
