"""create push_subscription table

Revision ID: d8a2c6f931e4
Revises: c4e8f1a26d7b
Create Date: 2026-07-21 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a2c6f931e4'
down_revision: Union[str, Sequence[str], None] = 'c4e8f1a26d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on 79f4a5571f9d/b3a7d2e19f45/c4e8f1a26d7b.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "push_subscription",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("p256dh_key", sa.String(), nullable=False),
        sa.Column("auth_key", sa.String(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_push_subscription_endpoint", "push_subscription", ["endpoint"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_push_subscription_endpoint", table_name="push_subscription")
    op.drop_table("push_subscription")
