"""create equipment_type table and add bed_equipment.garden_id

Revision ID: d9a1e4f70c58
Revises: c7d2f918a4b3
Create Date: 2026-07-29 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = 'd9a1e4f70c58'
down_revision: Union[str, Sequence[str], None] = 'c7d2f918a4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. #207: EquipmentType is a reference lookup
# table (see that model's own docstring) seeded via
# app/scripts/import_equipment_types.py from #206's data/equipment_types.json
# - no data insert here, unlike period_type's own migration, since the
# ticket explicitly calls for ETL import rather than hand-entered rows.
# bed_equipment.garden_id is a plain nullable FK, mutual exclusivity with
# bed_id enforced at the API layer (app/api/routes/bed_equipment.py), not a
# DB check constraint.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "equipment_type",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "bed_bound",
                "garden_bound_decorative",
                "garden_bound_functional",
                name="equipmentcategory",
            ),
            nullable=False,
        ),
        sa.Column("default_geometry", JSONB(), nullable=False),
        sa.Column("default_height_cm", sa.Float(), nullable=True),
    )
    op.create_index("ix_equipment_type_slug", "equipment_type", ["slug"], unique=True)

    op.add_column(
        "bed_equipment",
        sa.Column(
            "garden_id",
            sa.Integer(),
            sa.ForeignKey("garden.id"),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("bed_equipment", "garden_id")
    op.drop_index("ix_equipment_type_slug", table_name="equipment_type")
    op.drop_table("equipment_type")
    sa.Enum(name="equipmentcategory").drop(op.get_bind(), checkfirst=True)
