"""add plant growth_habit

Revision ID: e2c5a917b6d4
Revises: a7c39e5f2b18
Create Date: 2026-07-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c5a917b6d4'
down_revision: Union[str, Sequence[str], None] = 'a7c39e5f2b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on f1b7e4a92c3d and earlier migrations. Free-text scalar column,
# same style/nullability as soil_type/composting_needs on `plant`.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("plant", sa.Column("growth_habit", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("plant", "growth_habit")
