"""add irrigation_part diagram position and connector size

Revision ID: e4f6a2c9d105
Revises: d9a1e4f70c58
Create Date: 2026-07-29 02:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f6a2c9d105'
down_revision: Union[str, Sequence[str], None] = 'd9a1e4f70c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. #212: three plain additive nullable columns
# on irrigation_part for #209's canvas UI - connector_size_mm (advisory
# diameter-mismatch cue, never a validation error) and diagram_x/diagram_y
# (persisted node position on the pipe-network diagram, None = "not yet
# added to the diagram"). No data migration - existing rows get NULL in all
# three, which is exactly the "not recorded yet" state each field means.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("irrigation_part", sa.Column("connector_size_mm", sa.Float(), nullable=True))
    op.add_column("irrigation_part", sa.Column("diagram_x", sa.Float(), nullable=True))
    op.add_column("irrigation_part", sa.Column("diagram_y", sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("irrigation_part", "diagram_y")
    op.drop_column("irrigation_part", "diagram_x")
    op.drop_column("irrigation_part", "connector_size_mm")
