"""add bed_equipment.condition

Revision ID: e6a8c0d2f4b7
Revises: d4f6b8c0a2e5
Create Date: 2026-08-04 08:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a8c0d2f4b7'
down_revision: Union[str, Sequence[str], None] = 'd4f6b8c0a2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130), and
# same "add_column doesn't manage an enum type's lifecycle the way
# create_table does" pattern cd2f3a9b9ded (add plant life cycle) already
# established for adding an enum column to an existing table. #225: what
# happened to a piece of equipment when it was last unplaced - every
# existing row defaults to "good" (returned to usable inventory), the same
# default the model itself uses.
_equipment_condition_enum = sa.Enum("good", "damaged", "retired", name="equipmentcondition")


def upgrade() -> None:
    """Upgrade schema."""
    _equipment_condition_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "bed_equipment",
        sa.Column("condition", _equipment_condition_enum, nullable=False, server_default="good"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("bed_equipment", "condition")
    _equipment_condition_enum.drop(op.get_bind(), checkfirst=True)
