"""create decoration table

Revision ID: f1a2b3c4d5e6
Revises: e4f6a2c9d105
Create Date: 2026-08-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, Sequence[str], None] = 'e4f6a2c9d105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #241:
# Decoration - a purely cosmetic garden object (path, bench, garden gnome,
# etc.), deliberately the simplest table in the schema: no FKs to anything,
# and nothing else references it, so no cascade-delete concerns like Bed's.
# See app/models/decoration.py.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "decoration",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False, server_default="#78716c"),
        sa.Column("border_geometry", JSONB(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("decoration")
