"""add plant parent_plant_slug

Revision ID: f1b7e4a92c3d
Revises: d8a2c6f931e4
Create Date: 2026-07-21 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b7e4a92c3d'
down_revision: Union[str, Sequence[str], None] = 'd8a2c6f931e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on 79f4a5571f9d and later migrations (env.py only imports
# app.models.bed/plant for target_metadata, so most other tables would be
# misread as "removed" by autogenerate). This one specifically only touches
# `plant`, which env.py *does* import, but written by hand anyway for
# consistency/certainty with the rest of this migration chain.


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("plant", sa.Column("parent_plant_slug", sa.String(), nullable=True))
    op.create_foreign_key(
        "fk_plant_parent_plant_slug", "plant", "plant", ["parent_plant_slug"], ["slug"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_plant_parent_plant_slug", "plant", type_="foreignkey")
    op.drop_column("plant", "parent_plant_slug")
