"""create resource_pack and irrigation_part_type tables

Revision ID: f40407484fb2
Revises: a3f8c1d94e26
Create Date: 2026-08-04 23:04:22.421171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40407484fb2'
down_revision: Union[str, Sequence[str], None] = 'a3f8c1d94e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Autogenerated then hand-cleaned (dropped the sqlmodel.sql.sqltypes.AutoString
# references autogenerate emits with no accompanying import - every other
# migration in this project spells string columns as plain sa.String()).
# #251: ResourcePack (see app/models/resource_pack.py) is a new, empty-by-
# default grouping table; IrrigationPartType (app/models/irrigation_part_type.py)
# is the real catalog for IrrigationPart.part_type, same "seeded lookup,
# matched by normalized string, not a hard FK against IrrigationPart" pattern
# as EquipmentType/BedEquipment.equipment_type - but IrrigationPartType DOES
# carry a hard FK to its owning ResourcePack. No data insert here (unlike
# equipment_type's own migration) - seeding a real "Gardena" pack is flagged
# as a data-engineer follow-up (#251's own note), not this ticket's scope.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "resource_pack",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
    )
    op.create_index("ix_resource_pack_name", "resource_pack", ["name"], unique=True)

    op.create_table(
        "irrigation_part_type",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("resource_pack_id", sa.Integer(), sa.ForeignKey("resource_pack.id"), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("connection_count", sa.Integer(), nullable=False),
        sa.Column("part_number", sa.String(), nullable=True),
        sa.Column("icon_key", sa.String(), nullable=True),
    )
    op.create_index(
        "ix_irrigation_part_type_resource_pack_id", "irrigation_part_type", ["resource_pack_id"], unique=False
    )
    op.create_index("ix_irrigation_part_type_slug", "irrigation_part_type", ["slug"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_irrigation_part_type_slug", table_name="irrigation_part_type")
    op.drop_index("ix_irrigation_part_type_resource_pack_id", table_name="irrigation_part_type")
    op.drop_table("irrigation_part_type")
    op.drop_index("ix_resource_pack_name", table_name="resource_pack")
    op.drop_table("resource_pack")
