"""action due date window and dependencies

Revision ID: f4a8c2e517b9
Revises: a1e4c7b3f962
Create Date: 2026-07-28 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a8c2e517b9'
down_revision: Union[str, Sequence[str], None] = 'a1e4c7b3f962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata
# convention noted on earlier hand-written migrations (issue #130). #192:
# the automatic garden-task-generation engine needs Action.due_date to
# become a *window* (due_date_start/due_date_end) instead of a single
# instant, a new `thin` ActionType value, and a lightweight self-FK for
# "sowing can't start before bed prep is done" style dependencies - see
# app/models/action.py's own docstring for the full rationale.

_ACTION_TYPE_VALUES = (
    "fertilize",
    "compost",
    "prepare_bed",
    "sow",
    "plant",
    "install_equipment",
    "remove_equipment",
    "harvest",
    "clear",
    "collect_seeds",
)


def upgrade() -> None:
    """Upgrade schema."""
    # New enum value - safe to add inside this migration's own transaction
    # since nothing in this same migration reads/writes a row using it.
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'thin'")

    op.add_column("action", sa.Column("due_date_start", sa.Date(), nullable=True))
    op.add_column("action", sa.Column("due_date_end", sa.Date(), nullable=True))
    # Existing single-instant due_date collapses to a same-day window
    # rather than being lost outright.
    op.execute("UPDATE action SET due_date_start = due_date, due_date_end = due_date")
    op.drop_column("action", "due_date")

    op.add_column("action", sa.Column("depends_on_action_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_action_depends_on_action_id",
        "action",
        "action",
        ["depends_on_action_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_action_depends_on_action_id", "action", type_="foreignkey")
    op.drop_column("action", "depends_on_action_id")

    op.add_column("action", sa.Column("due_date", sa.Date(), nullable=True))
    op.execute("UPDATE action SET due_date = due_date_end")
    op.drop_column("action", "due_date_end")
    op.drop_column("action", "due_date_start")

    # Postgres has no "DROP VALUE" for an enum - rebuild the type without
    # 'thin' instead. Fails (correctly) if any row still has
    # action_type = 'thin' at this point, same as any other downgrade that
    # can't coexist with data written under the newer schema.
    op.execute("ALTER TYPE actiontype RENAME TO actiontype_old")
    restored_enum = sa.Enum(*_ACTION_TYPE_VALUES, name="actiontype")
    restored_enum.create(op.get_bind())
    op.execute(
        "ALTER TABLE action ALTER COLUMN action_type TYPE actiontype "
        "USING action_type::text::actiontype"
    )
    op.execute("DROP TYPE actiontype_old")
