"""create irrigation_part_instance table, repoint irrigation_connection at it

Revision ID: f7b2d4a6c803
Revises: e6a8c0d2f4b7
Create Date: 2026-08-04 03:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b2d4a6c803'
down_revision: Union[str, Sequence[str], None] = 'e6a8c0d2f4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated - same alembic/env.py target_metadata gap
# noted on earlier migrations. #254: IrrigationPart was "one row per part
# type", but IrrigationConnection/diagram_x/diagram_y assumed one placed
# node per part too - that breaks once you own more than one physical unit
# of the same part, connected to different neighbors. Splits per-instance
# placement/connections out into a new irrigation_part_instance table and
# re-points irrigation_connection.from_part_id/to_part_id at it (renamed
# from_instance_id/to_instance_id).
#
# Backfill (real data risk - checked row counts on garden-planner-dev's
# `garden` database before deploying this, see #254's deploy notes): every
# irrigation_part row that either has a diagram position already or is
# referenced by an existing irrigation_connection gets exactly one
# irrigation_part_instance created for it (copying its diagram_x/diagram_y),
# preserving the pre-#254 "one placed node per part" reality exactly -
# existing connections are remapped from the part's id to that one new
# instance's id, so nothing is orphaned or silently dropped.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "irrigation_part_instance",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("part_id", sa.Integer(), sa.ForeignKey("irrigation_part.id"), nullable=False),
        sa.Column("diagram_x", sa.Float(), nullable=True),
        sa.Column("diagram_y", sa.Float(), nullable=True),
    )

    # One instance per part that was actually placed and/or already
    # connected pre-#254 - see module docstring.
    op.execute(
        """
        INSERT INTO irrigation_part_instance (part_id, diagram_x, diagram_y)
        SELECT id, diagram_x, diagram_y
        FROM irrigation_part
        WHERE diagram_x IS NOT NULL
           OR diagram_y IS NOT NULL
           OR id IN (SELECT from_part_id FROM irrigation_connection)
           OR id IN (SELECT to_part_id FROM irrigation_connection)
        """
    )

    op.add_column("irrigation_connection", sa.Column("from_instance_id", sa.Integer(), nullable=True))
    op.add_column("irrigation_connection", sa.Column("to_instance_id", sa.Integer(), nullable=True))

    op.execute(
        """
        UPDATE irrigation_connection c
        SET from_instance_id = ipi.id
        FROM irrigation_part_instance ipi
        WHERE ipi.part_id = c.from_part_id
        """
    )
    op.execute(
        """
        UPDATE irrigation_connection c
        SET to_instance_id = ipi.id
        FROM irrigation_part_instance ipi
        WHERE ipi.part_id = c.to_part_id
        """
    )

    op.alter_column("irrigation_connection", "from_instance_id", nullable=False)
    op.alter_column("irrigation_connection", "to_instance_id", nullable=False)
    op.create_foreign_key(
        "irrigation_connection_from_instance_id_fkey",
        "irrigation_connection",
        "irrigation_part_instance",
        ["from_instance_id"],
        ["id"],
    )
    op.create_foreign_key(
        "irrigation_connection_to_instance_id_fkey",
        "irrigation_connection",
        "irrigation_part_instance",
        ["to_instance_id"],
        ["id"],
    )
    op.drop_column("irrigation_connection", "from_part_id")
    op.drop_column("irrigation_connection", "to_part_id")

    op.drop_column("irrigation_part", "diagram_x")
    op.drop_column("irrigation_part", "diagram_y")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column("irrigation_part", sa.Column("diagram_x", sa.Float(), nullable=True))
    op.add_column("irrigation_part", sa.Column("diagram_y", sa.Float(), nullable=True))

    op.add_column("irrigation_connection", sa.Column("from_part_id", sa.Integer(), nullable=True))
    op.add_column("irrigation_connection", sa.Column("to_part_id", sa.Integer(), nullable=True))

    op.execute(
        """
        UPDATE irrigation_connection c
        SET from_part_id = ipi.part_id
        FROM irrigation_part_instance ipi
        WHERE ipi.id = c.from_instance_id
        """
    )
    op.execute(
        """
        UPDATE irrigation_connection c
        SET to_part_id = ipi.part_id
        FROM irrigation_part_instance ipi
        WHERE ipi.id = c.to_instance_id
        """
    )
    # Lossy if #254's model was ever used to place more than one instance
    # per part - only the lowest-id instance's position survives the
    # downgrade, same "best effort, not perfectly reversible" tradeoff any
    # split-a-table-apart migration's downgrade has.
    op.execute(
        """
        UPDATE irrigation_part p
        SET diagram_x = ipi.diagram_x, diagram_y = ipi.diagram_y
        FROM (
            SELECT DISTINCT ON (part_id) part_id, diagram_x, diagram_y
            FROM irrigation_part_instance
            ORDER BY part_id, id
        ) ipi
        WHERE ipi.part_id = p.id
        """
    )

    op.alter_column("irrigation_connection", "from_part_id", nullable=False)
    op.alter_column("irrigation_connection", "to_part_id", nullable=False)
    op.create_foreign_key(
        "irrigation_connection_from_part_id_fkey",
        "irrigation_connection",
        "irrigation_part",
        ["from_part_id"],
        ["id"],
    )
    op.create_foreign_key(
        "irrigation_connection_to_part_id_fkey",
        "irrigation_connection",
        "irrigation_part",
        ["to_part_id"],
        ["id"],
    )
    op.drop_column("irrigation_connection", "from_instance_id")
    op.drop_column("irrigation_connection", "to_instance_id")

    op.drop_table("irrigation_part_instance")
